version: "2"
services:
  postgres_13.3:
    image: postgres:13.3
    hostname: postgres
    container_name: postgres_13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"